title: "dataset"
allOf:
  - $ref: "Base.yml"
  - properties:
      status:
        type: string
        enum: ["IN_QUEUE", "LOADING", "FINISHED", "ERROR"]
        example: "FINISHED"
        default: "IN_QUEUE"
        description: "The status of the dataset creation."

      group:
        type: string
        nullable: true
        default: null
        description: "In which group the dataset belongs to."

      order:
        type: integer
        nullable: true
        default: null
        description: "The order of the dataset in the group."